# This file was generated by GoReleaser. DO NOT EDIT.
class Gig < Formula
  desc "gitignore file generator"
  homepage "https://github.com/shihanng/gig"
  version "0.8.0-alpha.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shihanng/gig/releases/download/v0.8.0-alpha.0/gig_0.8.0-alpha.0_Darwin_x86_64.tar.gz"
    sha256 "a6b76a21c2f41fc1990203c0ed71e1a4627f7ee804923512144a15288724cbd5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/gig/releases/download/v0.8.0-alpha.0/gig_0.8.0-alpha.0_Linux_x86_64.tar.gz"
      sha256 "a31e0e6156d2dbd84937def5eeac3719540a7258c16ff994dac95512eaa208f0"
    end
  end
  
  depends_on "fzf"

  def install
    bin.install Dir['gig']
  end

  test do
    system "#{bin}/gig"
  end
end
