# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gig < Formula
  desc "gitignore file generator"
  homepage "https://github.com/shihanng/gig"
  version "0.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/gig/releases/download/v0.8.2/gig_0.8.2_Darwin_x86_64.tar.gz"
      sha256 "fb69c83372fd0e40fc6a1fb88e110844a6ef5a8425730f6f1777140cc98a60d0"

      def install
        bin.install Dir['gig']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/gig/releases/download/v0.8.2/gig_0.8.2_Linux_x86_64.tar.gz"
      sha256 "d2b514d35a605a91c7c479105636cb40e85dc518b5da866ef40b2d67a63e791c"

      def install
        bin.install Dir['gig']
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shihanng/gig/releases/download/v0.8.2/gig_0.8.2_Linux_arm64.tar.gz"
      sha256 "5065db2a87fba38928edf58fa0e67bf8ea1d900283fc0563d505ba86b671b715"

      def install
        bin.install Dir['gig']
      end
    end
  end

  depends_on "fzf"

  test do
    system "#{bin}/gig"
  end
end
